import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createReaderPreferences} from '../electron/preferences.mjs';
test('fit preferences survive a new app instance and reject invalid data',async()=>{const dir=await mkdtemp(join(tmpdir(),'reader-preferences-'));try{const path=join(dir,'reader.json'),first=await createReaderPreferences(path);assert.equal(first.load().fit,'width');await Promise.all([first.save({fit:'manual',zoom:1.4}),first.save({fit:'height',zoom:.8,translationMode:'reading'})]);const reopened=await createReaderPreferences(path);assert.deepEqual(reopened.load(),{engine:'pdf_inspector',fit:'height',zoom:.8,translationMode:'reading',direction:'vertical',columns:1});await reopened.save({fit:'height',zoom:.8,translationMode:'full'});assert.equal((await createReaderPreferences(path)).load().translationMode,'full');await reopened.save({engine:'pdf_inspector',fit:'height',zoom:.8,translationMode:'reading',direction:'vertical',columns:1});await reopened.save({fit:'width',zoom:1,direction:'horizontal',columns:4});assert.equal((await createReaderPreferences(path)).load().direction,'horizontal');assert.equal((await createReaderPreferences(path)).load().columns,4);await reopened.save({fit:'height',zoom:.8,translationMode:'reading'});assert.throws(()=>reopened.save({fit:'width',zoom:1,columns:3}));assert.throws(()=>reopened.save({fit:'window',zoom:100}));assert.deepEqual(reopened.load(),{engine:'pdf_inspector',fit:'height',zoom:.8,translationMode:'reading',direction:'vertical',columns:1});}finally{await rm(dir,{recursive:true,force:true});}});

test('kernel survives reopening and legacy window saves without reverting the selection',async()=>{const dir=await mkdtemp(join(tmpdir(),'kernel-preferences-'));try{const path=join(dir,'reader.json');const first=await createReaderPreferences(path);for(const engine of ['pdf_math_fast','pdf_math_precise','pdf_inspector']){await first.save({fit:'width',zoom:1,engine});await first.save({fit:'height',zoom:.8});assert.equal((await createReaderPreferences(path)).load().engine,engine);}assert.throws(()=>first.save({fit:'width',zoom:1,engine:'invalid'}));assert.equal(first.load().engine,'pdf_inspector');}finally{await rm(dir,{recursive:true,force:true});}});
