import {test} from 'node:test';import assert from 'node:assert/strict';
import {buildReaderLayout,visibleReaderWindow,buildThumbnailLayout,visibleThumbnailWindow} from '../src/reader-layout.mjs';
const pages=Array.from({length:1000},(_,i)=>({number:i+1,width:i%2?792:612,height:i%2?612:792}));
test('mixed-size row geometry preserves column widths, gaps and four buffered rows',()=>{for(const columns of [1,2,4]){const layout=buildReaderLayout(pages,1,'vertical',columns),row=layout.rows[80],bounds={top:row.offset+100,bottom:row.offset+600,left:0,right:layout.width};const result=visibleReaderWindow(layout,bounds);assert.equal(result.firstRow,76);assert.equal(result.lastRow,84);assert.equal(result.numbers.length,9*columns);assert.equal(layout.frames[columns].y-layout.frames[0].height,24);assert.ok(result.visible.every(v=>v.row===80));assert.equal(layout.height,layout.rows.at(-1).offset+layout.rows.at(-1).extent);}});
test('horizontal mixed pages center vertically and only nearby pages enter the window',()=>{const layout=buildReaderLayout(pages,.75,'horizontal',4),frame=layout.frames[500],result=visibleReaderWindow(layout,{left:frame.x+10,right:frame.x+300,top:0,bottom:layout.height});assert.deepEqual(result.visible.map(p=>p.number),[501]);assert.deepEqual(result.numbers,[497,498,499,500,501,502,503,504,505]);assert.equal(layout.frames[1].y,(layout.height-layout.frames[1].height)/2);assert.equal(layout.frames[1].x-layout.frames[0].width,24);});
test('large list thumbnail lookup is bounded and retains aspect-ratio geometry',()=>{const layout=buildThumbnailLayout(pages),f=layout.frames[900],result=visibleThumbnailWindow(layout,f.offset,700);assert.ok(result.length<10);assert.ok(result.some(p=>p.number===901));assert.equal(f.width/f.imageHeight,pages[900].width/pages[900].height);assert.equal(layout.height,layout.frames.at(-1).offset+layout.frames.at(-1).height);});
test('mixed-width pages expose viewport area when ratio favors the smaller page',()=>{const layout=buildReaderLayout([{number:1,width:100,height:100},{number:2,width:400,height:100}],1,'vertical',2),result=visibleReaderWindow(layout,{left:0,right:300,top:0,bottom:102}),small=result.visible.find(p=>p.number===1),large=result.visible.find(p=>p.number===2);assert.ok(small.ratio>large.ratio);assert.ok(large.area>small.area);assert.equal(result.visible.reduce((page,entry)=>entry.area>page.area?entry:page).number,2);assert.equal(small.area,102*102);assert.equal(large.area,174*102);});
test('horizontal visibility reports area for a horizontally clipped page',()=>{const layout=buildReaderLayout([{number:11,width:200,height:100},{number:12,width:400,height:100}],1,'horizontal'),result=visibleReaderWindow(layout,{left:300,right:500,top:0,bottom:layout.height});assert.deepEqual(result.visible.map(p=>p.number),[12]);assert.equal(result.visible[0].area,200*102);assert.equal(result.visible[0].ratio,200/402);assert.ok(result.visible[0].area<layout.frames[1].width*layout.frames[1].height);});

test('continuous pages have no border allocation or gaps in every layout',()=>{const uniform=Array.from({length:8},(_,i)=>({number:i+1,width:612,height:792}));for(const direction of ['vertical','horizontal'])for(const columns of [1,2,4]){const layout=buildReaderLayout(uniform,.75,direction,columns,0,0);assert.equal(layout.frames[0].width,459);assert.equal(layout.frames[0].height,594);for(let i=1;i<layout.frames.length;i++){const frame=layout.frames[i],previous=layout.frames[i-1];if(direction==='horizontal'||i%columns)assert.equal(frame.x,previous.x+previous.width);else assert.equal(frame.y,previous.y+previous.height);}}});
