const messages = {
  en: [
    'Keyboard Shortcuts',
    'Click a binding, then press the new shortcut. Changes are saved immediately.',
    'Press shortcut…',
    'Not assigned',
    'Clear',
    'Restore default',
    'Restore all defaults',
    'Cancel',
    'This shortcut is already in use.',
    'Unable to save shortcut.',
    'Keyboard shortcuts require the desktop app.',
    'Menu actions',
    'Page navigation',
  ],
  'zh-CN': [
    '快捷键',
    '点击绑定后按下新的快捷键，修改会立即保存并生效。',
    '请按下快捷键…',
    '未绑定',
    '清除',
    '恢复默认',
    '恢复全部默认值',
    '取消',
    '此快捷键已被占用。',
    '无法保存快捷键。',
    '快捷键设置需要使用桌面应用。',
    '菜单操作',
    '页面浏览',
  ],
  'zh-TW': [
    '快速鍵',
    '點擊綁定後按下新的快速鍵，修改會立即儲存並生效。',
    '請按下快速鍵…',
    '未綁定',
    '清除',
    '恢復預設',
    '恢復全部預設值',
    '取消',
    '此快速鍵已被使用。',
    '無法儲存快速鍵。',
    '快速鍵設定需要使用桌面應用程式。',
    '選單操作',
    '頁面瀏覽',
  ],
  ja: [
    'キーボードショートカット',
    '割り当てをクリックして新しいキーを押します。変更はすぐに保存されます。',
    'キーを押してください…',
    '未割り当て',
    '解除',
    '既定に戻す',
    'すべて既定に戻す',
    'キャンセル',
    'このショートカットは使用されています。',
    '保存できませんでした。',
    'デスクトップアプリで設定できます。',
    'メニュー操作',
    'ページ移動',
  ],
  ko: [
    '키보드 단축키',
    '단축키를 클릭한 후 새 키를 누르세요. 변경 사항은 즉시 저장됩니다.',
    '키를 누르세요…',
    '지정 안 됨',
    '해제',
    '기본값 복원',
    '모든 기본값 복원',
    '취소',
    '이미 사용 중인 단축키입니다.',
    '저장할 수 없습니다.',
    '데스크톱 앱에서 설정할 수 있습니다.',
    '메뉴 작업',
    '페이지 탐색',
  ],
  fr: [
    'Raccourcis clavier',
    'Cliquez sur un raccourci, puis appuyez sur les nouvelles touches. Les changements sont enregistrés immédiatement.',
    'Appuyez sur les touches…',
    'Non attribué',
    'Effacer',
    'Rétablir',
    'Tout rétablir',
    'Annuler',
    'Ce raccourci est déjà utilisé.',
    'Impossible d’enregistrer le raccourci.',
    'Ces réglages nécessitent l’application de bureau.',
    'Actions des menus',
    'Navigation des pages',
  ],
  es: [
    'Atajos de teclado',
    'Haz clic en un atajo y pulsa las nuevas teclas. Los cambios se guardan inmediatamente.',
    'Pulsa las teclas…',
    'Sin asignar',
    'Borrar',
    'Restaurar',
    'Restaurar todos',
    'Cancelar',
    'Este atajo ya está en uso.',
    'No se pudo guardar el atajo.',
    'Estos ajustes requieren la aplicación de escritorio.',
    'Acciones de menú',
    'Navegación de páginas',
  ],
  bn: [
    'কীবোর্ড শর্টকাট',
    'একটি বাঁধাইতে ক্লিক করে নতুন শর্টকাট চাপুন। পরিবর্তন সঙ্গে সঙ্গে সংরক্ষিত হয়।',
    'শর্টকাট চাপুন…',
    'নির্ধারিত নয়',
    'মুছুন',
    'ডিফল্ট পুনরুদ্ধার',
    'সব ডিফল্ট পুনরুদ্ধার',
    'বাতিল',
    'এই শর্টকাটটি ইতিমধ্যে ব্যবহৃত হচ্ছে।',
    'শর্টকাট সংরক্ষণ করা যায়নি।',
    'কীবোর্ড শর্টকাটের জন্য ডেস্কটপ অ্যাপ প্রয়োজন।',
    'মেনু অ্যাকশন',
    'পৃষ্ঠা নেভিগেশন',
  ],
  de: [
    'Tastenkürzel',
    'Klicke auf eine Zuordnung und drücke dann das neue Kürzel. Änderungen werden sofort gespeichert.',
    'Kürzel drücken…',
    'Nicht zugewiesen',
    'Löschen',
    'Standard wiederherstellen',
    'Alle Standards wiederherstellen',
    'Abbrechen',
    'Dieses Kürzel wird bereits verwendet.',
    'Kürzel konnte nicht gespeichert werden.',
    'Tastenkürzel benötigen die Desktop-App.',
    'Menüaktionen',
    'Seitennavigation',
  ],
  hi: [
    'कीबोर्ड शॉर्टकट',
    'किसी बाइंडिंग पर क्लिक करें, फिर नया शॉर्टकट दबाएँ। बदलाव तुरंत सहेजे जाते हैं।',
    'शॉर्टकट दबाएँ…',
    'निर्धारित नहीं',
    'साफ़ करें',
    'डिफ़ॉल्ट पुनर्स्थापित करें',
    'सभी डिफ़ॉल्ट पुनर्स्थापित करें',
    'रद्द करें',
    'यह शॉर्टकट पहले से उपयोग में है।',
    'शॉर्टकट सहेजा नहीं जा सका।',
    'कीबोर्ड शॉर्टकट के लिए डेस्कटॉप ऐप आवश्यक है।',
    'मेनू क्रियाएँ',
    'पृष्ठ नेविगेशन',
  ],
  pcm: [
    'Keyboard shortcuts',
    'Click one binding, then press the new shortcut. Changes go save immediately.',
    'Press shortcut…',
    'No shortcut set',
    'Clear',
    'Restore default',
    'Restore all defaults',
    'Cancel',
    'This shortcut don dey use already.',
    'Shortcut no fit save.',
    'You need the desktop app to use keyboard shortcuts.',
    'Menu actions',
    'Page navigation',
  ],
  pt: [
    'Atalhos de teclado',
    'Clique em uma atribuição e pressione o novo atalho. As alterações são salvas imediatamente.',
    'Pressione o atalho…',
    'Não atribuído',
    'Limpar',
    'Restaurar padrão',
    'Restaurar todos os padrões',
    'Cancelar',
    'Este atalho já está em uso.',
    'Não foi possível salvar o atalho.',
    'Os atalhos de teclado exigem o aplicativo para computador.',
    'Ações do menu',
    'Navegação de páginas',
  ],
  ru: [
    'Сочетания клавиш',
    'Нажмите на назначение, затем нажмите новое сочетание. Изменения сохраняются сразу.',
    'Нажмите сочетание…',
    'Не назначено',
    'Очистить',
    'Восстановить по умолчанию',
    'Восстановить все значения по умолчанию',
    'Отмена',
    'Это сочетание уже используется.',
    'Не удалось сохранить сочетание.',
    'Для настройки сочетаний клавиш требуется приложение для компьютера.',
    'Действия меню',
    'Навигация по страницам',
  ],
  ar: [
    'اختصارات لوحة المفاتيح',
    'انقر على ارتباط ثم اضغط الاختصار الجديد. تُحفظ التغييرات فورًا.',
    'اضغط الاختصار…',
    'غير معيّن',
    'مسح',
    'استعادة الافتراضي',
    'استعادة جميع الإعدادات الافتراضية',
    'إلغاء',
    'هذا الاختصار مستخدم بالفعل.',
    'تعذّر حفظ الاختصار.',
    'تتطلب اختصارات لوحة المفاتيح تطبيق سطح المكتب.',
    'إجراءات القائمة',
    'التنقل بين الصفحات',
  ],
  arz: [
    'اختصارات الكيبورد',
    'دوس على الاختصار، وبعدها دوس الاختصار الجديد. التغييرات بتتحفظ فورًا.',
    'دوس الاختصار…',
    'مش متعيّن',
    'امسح',
    'رجّع الافتراضي',
    'رجّع كل الافتراضيات',
    'إلغاء',
    'الاختصار ده مستخدم قبل كده.',
    'مش قادرين نحفظ الاختصار.',
    'اختصارات الكيبورد محتاجة تطبيق سطح المكتب.',
    'عمليات القائمة',
    'التنقّل بين الصفحات',
  ],
  ur: [
    'کی بورڈ شارٹ کٹس',
    'کسی اسائنمنٹ پر کلک کریں، پھر نیا شارٹ کٹ دبائیں۔ تبدیلیاں فوراً محفوظ ہو جاتی ہیں۔',
    'شارٹ کٹ دبائیں…',
    'مختص نہیں',
    'صاف کریں',
    'طے شدہ بحال کریں',
    'تمام طے شدہ بحال کریں',
    'منسوخ کریں',
    'یہ شارٹ کٹ پہلے ہی استعمال ہو رہا ہے۔',
    'شارٹ کٹ محفوظ نہیں ہو سکا۔',
    'کی بورڈ شارٹ کٹس کے لیے ڈیسک ٹاپ ایپ درکار ہے۔',
    'مینو کے اعمال',
    'صفحے کی نیویگیشن',
  ],
};
export function shortcutLabels(locale) {
  const values = messages[locale] || messages.en;
  return Object.fromEntries(
    [
      'title',
      'hint',
      'record',
      'unassigned',
      'clear',
      'reset',
      'resetAll',
      'cancel',
      'conflict',
      'error',
      'desktop',
      'menu',
      'navigation',
    ].map((key, index) => [key, values[index]]),
  );
}
