const messages = {
  en: [
    'Keyboard Shortcuts',
    'Click a binding, then press the new shortcut. Changes are saved immediately.',
    'Press shortcut…',
    'Not assigned',
    'Clear',
    'Restore default',
    'Restore all defaults',
    'Cancel',
    'This shortcut is already in use.',
    'Unable to save shortcut.',
    'Keyboard shortcuts require the desktop app.',
    'Menu actions',
    'Page navigation',
  ],
  'zh-CN': [
    '快捷键',
    '点击绑定后按下新的快捷键，修改会立即保存并生效。',
    '请按下快捷键…',
    '未绑定',
    '清除',
    '恢复默认',
    '恢复全部默认值',
    '取消',
    '此快捷键已被占用。',
    '无法保存快捷键。',
    '快捷键设置需要使用桌面应用。',
    '菜单操作',
    '页面浏览',
  ],
  'zh-TW': [
    '快速鍵',
    '點擊綁定後按下新的快速鍵，修改會立即儲存並生效。',
    '請按下快速鍵…',
    '未綁定',
    '清除',
    '恢復預設',
    '恢復全部預設值',
    '取消',
    '此快速鍵已被使用。',
    '無法儲存快速鍵。',
    '快速鍵設定需要使用桌面應用程式。',
    '選單操作',
    '頁面瀏覽',
  ],
  ja: [
    'キーボードショートカット',
    '割り当てをクリックして新しいキーを押します。変更はすぐに保存されます。',
    'キーを押してください…',
    '未割り当て',
    '解除',
    '既定に戻す',
    'すべて既定に戻す',
    'キャンセル',
    'このショートカットは使用されています。',
    '保存できませんでした。',
    'デスクトップアプリで設定できます。',
    'メニュー操作',
    'ページ移動',
  ],
  ko: [
    '키보드 단축키',
    '단축키를 클릭한 후 새 키를 누르세요. 변경 사항은 즉시 저장됩니다.',
    '키를 누르세요…',
    '지정 안 됨',
    '해제',
    '기본값 복원',
    '모든 기본값 복원',
    '취소',
    '이미 사용 중인 단축키입니다.',
    '저장할 수 없습니다.',
    '데스크톱 앱에서 설정할 수 있습니다.',
    '메뉴 작업',
    '페이지 탐색',
  ],
  fr: [
    'Raccourcis clavier',
    'Cliquez sur un raccourci, puis appuyez sur les nouvelles touches. Les changements sont enregistrés immédiatement.',
    'Appuyez sur les touches…',
    'Non attribué',
    'Effacer',
    'Rétablir',
    'Tout rétablir',
    'Annuler',
    'Ce raccourci est déjà utilisé.',
    'Impossible d’enregistrer le raccourci.',
    'Ces réglages nécessitent l’application de bureau.',
    'Actions des menus',
    'Navigation des pages',
  ],
  es: [
    'Atajos de teclado',
    'Haz clic en un atajo y pulsa las nuevas teclas. Los cambios se guardan inmediatamente.',
    'Pulsa las teclas…',
    'Sin asignar',
    'Borrar',
    'Restaurar',
    'Restaurar todos',
    'Cancelar',
    'Este atajo ya está en uso.',
    'No se pudo guardar el atajo.',
    'Estos ajustes requieren la aplicación de escritorio.',
    'Acciones de menú',
    'Navegación de páginas',
  ],
};
export function shortcutLabels(locale) {
  const values = messages[locale] || messages.en;
  return Object.fromEntries(
    [
      'title',
      'hint',
      'record',
      'unassigned',
      'clear',
      'reset',
      'resetAll',
      'cancel',
      'conflict',
      'error',
      'desktop',
      'menu',
      'navigation',
    ].map((key, index) => [key, values[index]]),
  );
}
