<script setup>
import {MacSwitch} from '@macvue/core';
defineProps({appearance:String,accentColor:String,reduceMotion:Boolean,reduceTransparency:Boolean,reducePadding:Boolean});
const emit=defineEmits(['update:appearance','update:accentColor','update:reduceMotion','update:reduceTransparency','update:reducePadding']);
const themes=[['light','Light'],['dark','Dark'],['system','Auto']];
const colors=[['system','System'],['#007aff','Blue'],['#af52de','Purple'],['#ff2d55','Pink'],['#ff3b30','Red'],['#ff9500','Orange'],['#ffcc00','Yellow'],['#34c759','Green'],['#8e8e93','Gray'],['#3d647a','This Mac']];
</script>
<template>
<section class="settings-section appearance-section" aria-labelledby="settings-appearance"><h3 id="settings-appearance">Appearance</h3>
<div class="appearance-row"><span>Appearance</span><div class="appearance-options" role="group" aria-label="Appearance"><button v-for="[value,label] in themes" :key="value" class="appearance-choice" :aria-pressed="appearance===value" @click="emit('update:appearance',value)"><span class="appearance-preview" :data-preview="value" aria-hidden="true"><i class="preview-window"><i></i><b></b><b></b></i><i class="preview-panel"><b></b><b></b><b></b></i></span><span>{{label}}</span></button></div></div>
<div class="appearance-row color-row"><span>Color</span><div class="color-options" role="group" aria-label="Accent color"><button v-for="[value,label] in colors" :key="value" class="color-choice" :aria-label="label+' accent color'" :aria-pressed="accentColor===value" @click="emit('update:accentColor',value)"><span class="color-swatch" :class="{spectrum:value==='system'}" :style="value!=='system'?{background:value}:{}"></span><span>{{label}}</span></button><label class="color-choice custom-color" :class="{selected:accentColor!=='system'&&!colors.some(c=>c[0]===accentColor)}"><span class="color-swatch spectrum" :style="accentColor!=='system'?{background:accentColor}:{}"><input type="color" aria-label="Custom accent color" :value="accentColor==='system'?'#3d647a':accentColor" @input="emit('update:accentColor',$event.target.value)"/></span><span>Custom</span></label></div></div>
<div class="appearance-effects"><span>Effects</span><div><div class="setting-row"><span id="reduce-motion-label">Reduce motion</span><MacSwitch :model-value="reduceMotion" aria-labelledby="reduce-motion-label" @update:model-value="emit('update:reduceMotion',$event)"/></div><div class="setting-row"><span id="reduce-transparency-label">Reduce transparency</span><MacSwitch :model-value="reduceTransparency" aria-labelledby="reduce-transparency-label" @update:model-value="emit('update:reduceTransparency','update:reducePadding',$event)"/></div><div class="setting-row"><span id="reduce-padding-label">Reduce padding</span><MacSwitch :model-value="reducePadding" aria-labelledby="reduce-padding-label" @update:model-value="emit('update:reducePadding',$event)"/></div></div></div>
</section>
</template>
