<script setup>
import {watch} from 'vue';
import {MacSwitch,MacPopUpButton,MacPopUpButtonItem} from './platform-controls.mjs';
import {t,setUILanguage} from './i18n.mjs';
const props=defineProps({appearance:String,accentColor:String,reduceMotion:Boolean,reduceTransparency:Boolean,reducePadding:Boolean,uiLanguage:{type:String,default:'en'}});
const emit=defineEmits(['update:appearance','update:accentColor','update:reduceMotion','update:reduceTransparency','update:reducePadding','update:uiLanguage']);
const themes=[['light','appearance.light'],['dark','appearance.dark'],['system','appearance.auto']];
const colors=[['system','appearance.system'],['#007aff','appearance.blue'],['#af52de','appearance.purple'],['#ff2d55','appearance.pink'],['#ff3b30','appearance.red'],['#ff9500','appearance.orange'],['#ffcc00','appearance.yellow'],['#34c759','appearance.green'],['#8e8e93','appearance.gray'],['#3d647a','appearance.slateBlue']];
const uiLanguages=[['en','appearance.english'],['zh-CN','appearance.simplifiedChinese'],['zh-TW','appearance.traditionalChinese'],['fr','appearance.french'],['es','appearance.spanish'],['ja','appearance.japanese'],['ko','appearance.korean']];
watch(()=>props.uiLanguage,code=>setUILanguage(code),{immediate:true});
function changeUILanguage(code){emit('update:uiLanguage',setUILanguage(code));}
</script>
<template>
<section class="settings-section appearance-section" aria-labelledby="settings-appearance"><h3 id="settings-appearance">{{t('appearance.section')}}</h3>
<div class="appearance-row"><span>{{t('appearance.appearance')}}</span><div class="appearance-options" role="group" :aria-label="t('appearance.appearance')"><button v-for="[value,label] in themes" :key="value" class="appearance-choice" :aria-pressed="appearance===value" @click="emit('update:appearance',value)"><span class="appearance-preview" :data-preview="value" aria-hidden="true"><i class="preview-window"><i></i><b></b><b></b></i><i class="preview-panel"><b></b><b></b><b></b></i></span><span>{{t(label)}}</span></button></div></div>
<div class="appearance-row color-row"><span>{{t('appearance.color')}}</span><div class="color-options" role="group" :aria-label="t('appearance.accentColor')"><button v-for="[value,label] in colors" :key="value" class="color-choice" :aria-label="t('appearance.accentColorOption',{name:t(label)})" :aria-pressed="accentColor===value" @click="emit('update:accentColor',value)"><span class="color-swatch" :class="{spectrum:value==='system'}" :style="value!=='system'?{background:value}:{}"></span><span>{{t(label)}}</span></button><label class="color-choice custom-color" :class="{selected:accentColor!=='system'&&!colors.some(c=>c[0]===accentColor)}"><span class="color-swatch spectrum" :style="accentColor!=='system'?{background:accentColor}:{}"><input type="color" :aria-label="t('appearance.customAccentColor')" :value="accentColor==='system'?'#3d647a':accentColor" @input="emit('update:accentColor',$event.target.value)"/></span><span>{{t('appearance.custom')}}</span></label></div></div>
<div class="appearance-row"><span>{{t('appearance.interfaceLanguage')}}</span><MacPopUpButton :teleport-to="false" :model-value="uiLanguage" :aria-label="t('appearance.interfaceLanguage')" @update:model-value="changeUILanguage"><MacPopUpButtonItem v-for="[value,label] in uiLanguages" :key="value" :value="value">{{t(label)}}</MacPopUpButtonItem></MacPopUpButton></div>
<div class="appearance-effects"><span>{{t('appearance.effects')}}</span><div><div class="setting-row"><span id="reduce-motion-label">{{t('appearance.reduceMotion')}}</span><MacSwitch :model-value="reduceMotion" aria-labelledby="reduce-motion-label" @update:model-value="emit('update:reduceMotion',$event)"/></div><div class="setting-row"><span id="reduce-transparency-label">{{t('appearance.reduceTransparency')}}</span><MacSwitch :model-value="reduceTransparency" aria-labelledby="reduce-transparency-label" @update:model-value="emit('update:reduceTransparency',$event)"/></div><div class="setting-row"><span id="reduce-padding-label">{{t('appearance.reducePadding')}}</span><MacSwitch :model-value="reducePadding" aria-labelledby="reduce-padding-label" @update:model-value="emit('update:reducePadding',$event)"/></div></div></div>
</section>
</template>
